### ISSUE TITLE
Compile errors version 2 and up

### ISSUE THREAD

**Issue by MartijnCalysto** [someweisguy/esp_dmx#104]
I probably do something wrong, but it works with version 1.1.3. I get errors like: "'DMX_PACKET_SIZE' was not declared in this scope"
I use Arduino IDE 2.2, installed ESP32 Wroom dev board. I like to compile ArtNet to DMX Gateway, but I've tried examples too. Booth give me this kind of errors...

Many thanks for making this library!!

**Comment by someweisguy** [comment]
Thank you for the kind words!

Is there a particular reason you are using esp_dmx v1.1.3? If not, I would recommend that you update to the latest version, v3.1.0. That should make the errors disappear.

**Comment by MartijnCalysto** [comment]
I did, but it's the other way around, version 1.1.3 works, higher versions don't...

**Comment by someweisguy** [comment]
> I use Arduino IDE 2.2, installed ESP32 Wroom dev board.

> I did, but it's the other way around, version 1.1.3 works, higher versions don't...

I see. Can you confirm which version of Arduino-ESP32 you are using? You should be using v2.0.3 or higher. I see that you are using IDE v2.2, but I'm specifically referring to the Arduino-ESP32 framework, not the IDE. You can verify this by checking the Boards Manager on the Arduino IDE and searching `esp32` to find "esp32 by Espressif Systems." I am currently using v2.0.14 without any issues.

**Comment by MartijnCalysto** [comment]
I've version 2.0.14 too...  I've used this link in the Additional Board Manager URLs field: https://espressif.github.io/arduino-esp32/package_esp32_index.json

From the json file:

`    "boards": [
            {
              "name": "ESP32 Dev Board"
            },
            {
              "name": "ESP32-S2 Dev Board"
            },
            {
              "name": "ESP32-S3 Dev Board"
            },
            {
              "name": "ESP32-C3 Dev Board"
            },
            {
              "name": "Arduino Nano ESP32"
            }
          ],`

Should I see those names as boards in the board library? Because I don't... all kinds of esp32 boards, but not with these names.

I've tested it again, with your dmxwrite example. ESP_DMX version 3.1.0. This is the error log:

**Comment by MartijnCalysto** [comment]
`C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:121:14: error: 'DMX_MAX_PACKET_SIZE' was not declared in this scope
 byte dataOut[DMX_MAX_PACKET_SIZE];
              ^~~~~~~~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:121:14: note: suggested alternative: 'ETH_MAX_PACKET_SIZE'
 byte dataOut[DMX_MAX_PACKET_SIZE];
              ^~~~~~~~~~~~~~~~~~~
              ETH_MAX_PACKET_SIZE
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:122:13: error: 'DMX_MAX_PACKET_SIZE' was not declared in this scope
 byte dataIn[DMX_MAX_PACKET_SIZE];
             ^~~~~~~~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:122:13: note: suggested alternative: 'ETH_MAX_PACKET_SIZE'
 byte dataIn[DMX_MAX_PACKET_SIZE];
             ^~~~~~~~~~~~~~~~~~~
             ETH_MAX_PACKET_SIZE
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino: In function 'void initDMXIn()':
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:302:30: error: 'DMX_DEFAULT_CONFIG' was not declared in this scope
   dmx_config_t dmxInConfig = DMX_DEFAULT_CONFIG;
                              ^~~~~~~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:302:30: note: suggested alternative: 'ETH_DEFAULT_CONFIG'
   dmx_config_t dmxInConfig = DMX_DEFAULT_CONFIG;
                              ^~~~~~~~~~~~~~~~~~
                              ETH_DEFAULT_CONFIG
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:303:3: error: 'dmx_param_config' was not declared in this scope
   dmx_param_config(dmxInPort, &dmxInConfig);
   ^~~~~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:303:3: note: suggested alternative: 'dmxInConfig'
   dmx_param_config(dmxInPort, &dmxInConfig);
   ^~~~~~~~~~~~~~~~
   dmxInConfig
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:314:33: error: 'DMX_MAX_PACKET_SIZE' was not declared in this scope
   dmx_driver_install(dmxInPort, DMX_MAX_PACKET_SIZE, queueSize, &queue, interruptPriority);
                                 ^~~~~~~~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:314:33: note: suggested alternative: 'ETH_MAX_PACKET_SIZE'
   dmx_driver_install(dmxInPort, DMX_MAX_PACKET_SIZE, queueSize, &queue, interruptPriority);
                                 ^~~~~~~~~~~~~~~~~~~
                                 ETH_MAX_PACKET_SIZE
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino: In function 'void initDMXOut()':
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:320:31: error: 'DMX_DEFAULT_CONFIG' was not declared in this scope
   dmx_config_t dmxOutConfig = DMX_DEFAULT_CONFIG;
                               ^~~~~~~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:320:31: note: suggested alternative: 'ETH_DEFAULT_CONFIG'
   dmx_config_t dmxOutConfig = DMX_DEFAULT_CONFIG;
                               ^~~~~~~~~~~~~~~~~~
                               ETH_DEFAULT_CONFIG
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:321:3: error: 'dmx_param_config' was not declared in this scope
   dmx_param_config(dmxOutPort, &dmxOutConfig);
   ^~~~~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:321:3: note: suggested alternative: 'dmxOutConfig'
   dmx_param_config(dmxOutPort, &dmxOutConfig);
   ^~~~~~~~~~~~~~~~
   dmxOutConfig
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:332:34: error: 'DMX_MAX_PACKET_SIZE' was not declared in this scope
   dmx_driver_install(dmxOutPort, DMX_MAX_PACKET_SIZE, queueSize, NULL, interruptPriority);
                                  ^~~~~~~~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:332:34: note: suggested alternative: 'ETH_MAX_PACKET_SIZE'
   dmx_driver_install(dmxOutPort, DMX_MAX_PACKET_SIZE, queueSize, NULL, interruptPriority);
                                  ^~~~~~~~~~~~~~~~~~~
                                  ETH_MAX_PACKET_SIZE
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:337:28: error: 'DMX_MODE_TX' was not declared in this scope
   dmx_set_mode(dmxOutPort, DMX_MODE_TX);
                            ^~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:337:28: note: suggested alternative: 'WIFI_MODE_MAX'
   dmx_set_mode(dmxOutPort, DMX_MODE_TX);
                            ^~~~~~~~~~~
                            WIFI_MODE_MAX
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:337:3: error: 'dmx_set_mode' was not declared in this scope
   dmx_set_mode(dmxOutPort, DMX_MODE_TX);
   ^~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:337:3: note: suggested alternative: 'dmx_set_pin'
   dmx_set_mode(dmxOutPort, DMX_MODE_TX);
   ^~~~~~~~~~~~
   dmx_set_pin
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:338:3: error: 'dataOut' was not declared in this scope
   dataOut[0] = 0;
   ^~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino: In function 'void onArtNetFrame(uint16_t, uint16_t, uint8_t, uint8_t*)':
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:345:47: error: 'DMX_MAX_PACKET_SIZE' was not declared in this scope
   for (int i = 1; i < numberOfChannels && i < DMX_MAX_PACKET_SIZE; ++i) {
                                               ^~~~~~~~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:345:47: note: suggested alternative: 'ETH_MAX_PACKET_SIZE'
   for (int i = 1; i < numberOfChannels && i < DMX_MAX_PACKET_SIZE; ++i) {
                                               ^~~~~~~~~~~~~~~~~~~
                                               ETH_MAX_PACKET_SIZE
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:346:5: error: 'dataOut' was not declared in this scope
     dataOut[i] = dmxData[i - 1];
     ^~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:349:153: error: 'dataOut' was not declared in this scope
   Serial.printf("<< ArtNet Uni %u Seq %03u Chans %u => DMX: %03d - %03d %03d %03d %03d - %03d %03d %03d %03d \n", universe, sequence, numberOfChannels, dataOut[0], dataOut[1], dataOut[2], dataOut[3], dataOut[4], dataOut[5], dataOut[6], dataOut[7], dataOut[8]);
                                                                                                                                                         ^~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:362:41: error: 'DMX_MAX_PACKET_SIZE' was not declared in this scope
   dmx_write_packet(dmxOutPort, dataOut, DMX_MAX_PACKET_SIZE);
                                         ^~~~~~~~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:362:41: note: suggested alternative: 'ETH_MAX_PACKET_SIZE'
   dmx_write_packet(dmxOutPort, dataOut, DMX_MAX_PACKET_SIZE);
                                         ^~~~~~~~~~~~~~~~~~~
                                         ETH_MAX_PACKET_SIZE
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:362:3: error: 'dmx_write_packet' was not declared in this scope
   dmx_write_packet(dmxOutPort, dataOut, DMX_MAX_PACKET_SIZE);
   ^~~~~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:362:3: note: suggested alternative: 'dmx_write_offset'
   dmx_write_packet(dmxOutPort, dataOut, DMX_MAX_PACKET_SIZE);
   ^~~~~~~~~~~~~~~~
   dmx_write_offset
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:363:3: error: 'dmx_tx_packet' was not declared in this scope
   dmx_tx_packet(dmxOutPort);
   ^~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:363:3: note: suggested alternative: 'dmx_packet_t'
   dmx_tx_packet(dmxOutPort);
   ^~~~~~~~~~~~~
   dmx_packet_t
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:364:32: error: 'DMX_TX_PACKET_TOUT_TICK' was not declared in this scope
   dmx_wait_tx_done(dmxOutPort, DMX_TX_PACKET_TOUT_TICK);
                                ^~~~~~~~~~~~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:364:32: note: suggested alternative: 'DMX_TIMEOUT_TICK'
   dmx_wait_tx_done(dmxOutPort, DMX_TX_PACKET_TOUT_TICK);
                                ^~~~~~~~~~~~~~~~~~~~~~~
                                DMX_TIMEOUT_TICK
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:364:3: error: 'dmx_wait_tx_done' was not declared in this scope
   dmx_wait_tx_done(dmxOutPort, DMX_TX_PACKET_TOUT_TICK);
   ^~~~~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:364:3: note: suggested alternative: 'dmx_wait_sent'
   dmx_wait_tx_done(dmxOutPort, DMX_TX_PACKET_TOUT_TICK);
   ^~~~~~~~~~~~~~~~
   dmx_wait_sent
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino: In function 'void dmxInLoop()':
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:370:3: error: 'dmx_event_t' was not declared in this scope
   dmx_event_t packet;
   ^~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:370:3: note: suggested alternative: 'eth_event_t'
   dmx_event_t packet;
   ^~~~~~~~~~~
   eth_event_t
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:376:29: error: 'packet' was not declared in this scope
   if (xQueueReceive(queue, &packet, DMX_RX_TIMEOUT)) {
                             ^~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:376:29: note: suggested alternative: 'pause'
   if (xQueueReceive(queue, &packet, DMX_RX_TIMEOUT)) {
                             ^~~~~~
                             pause
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:393:34: error: 'dataIn' was not declared in this scope
       dmx_read_packet(dmxInPort, dataIn, packet.size);
                                  ^~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:393:34: note: suggested alternative: 'atan'
       dmx_read_packet(dmxInPort, dataIn, packet.size);
                                  ^~~~~~
                                  atan
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:393:7: error: 'dmx_read_packet' was not declared in this scope
       dmx_read_packet(dmxInPort, dataIn, packet.size);
       ^~~~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:393:7: note: suggested alternative: 'dmx_read_offset'
       dmx_read_packet(dmxInPort, dataIn, packet.size);
       ^~~~~~~~~~~~~~~
       dmx_read_offset
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:397:46: error: 'DMX_MAX_PACKET_SIZE' was not declared in this scope
         dmx_write_packet(dmxOutPort, dataIn, DMX_MAX_PACKET_SIZE);
                                              ^~~~~~~~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:397:46: note: suggested alternative: 'ETH_MAX_PACKET_SIZE'
         dmx_write_packet(dmxOutPort, dataIn, DMX_MAX_PACKET_SIZE);
                                              ^~~~~~~~~~~~~~~~~~~
                                              ETH_MAX_PACKET_SIZE
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:397:9: error: 'dmx_write_packet' was not declared in this scope
         dmx_write_packet(dmxOutPort, dataIn, DMX_MAX_PACKET_SIZE);
         ^~~~~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:397:9: note: suggested alternative: 'dmx_write_offset'
         dmx_write_packet(dmxOutPort, dataIn, DMX_MAX_PACKET_SIZE);
         ^~~~~~~~~~~~~~~~
         dmx_write_offset
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:398:9: error: 'dmx_tx_packet' was not declared in this scope
         dmx_tx_packet(dmxOutPort);
         ^~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:398:9: note: suggested alternative: 'dmx_packet_t'
         dmx_tx_packet(dmxOutPort);
         ^~~~~~~~~~~~~
         dmx_packet_t
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:399:38: error: 'DMX_TX_PACKET_TOUT_TICK' was not declared in this scope
         dmx_wait_tx_done(dmxOutPort, DMX_TX_PACKET_TOUT_TICK);
                                      ^~~~~~~~~~~~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:399:38: note: suggested alternative: 'DMX_TIMEOUT_TICK'
         dmx_wait_tx_done(dmxOutPort, DMX_TX_PACKET_TOUT_TICK);
                                      ^~~~~~~~~~~~~~~~~~~~~~~
                                      DMX_TIMEOUT_TICK
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:399:9: error: 'dmx_wait_tx_done' was not declared in this scope
         dmx_wait_tx_done(dmxOutPort, DMX_TX_PACKET_TOUT_TICK);
         ^~~~~~~~~~~~~~~~
C:\Users\marti\OneDrive\Documenten\Arduino\projects\ESP32_ArtNet_DMX_Gateway\ESP32_ArtNet_DMX_Gateway.ino:399:9: note: suggested alternative: 'dmx_wait_sent'
         dmx_wait_tx_done(dmxOutPort, DMX_TX_PACKET_TOUT_TICK);
         ^~~~~~~~~~~~~~~~
         dmx_wait_sent

exit status 1

Compilation error: 'DMX_MAX_PACKET_SIZE' was not declared in this scope`

**Comment by someweisguy** [comment]
Oh, I think I see the issue. The constants in that error message are no longer valid. I think somehow the examples you are using are the examples for the v1 or v2 library. v3 is not compatible with v1 or v2. 

[Here](https://github.com/someweisguy/esp_dmx/blob/v3.1.0/examples/DMXWrite/DMXWrite.ino) is the link to the v3 DMX Write example. I just tested this code on Arduino and it compiled for me.

**Comment by MartijnCalysto** [comment]
Don't know why but this was it!! Yes!! Do you know a project like ConnoDMX that's works with eps_dmx v3?

**Comment by someweisguy** [comment]
That's great to hear!

I just released v3, so I am not aware of any other projects currently using it.
