### ISSUE TITLE
doesn't compile on esp-idf 5.3

### ISSUE THREAD

**Issue by juanpgg-git** [someweisguy/esp_dmx#181]
`C:/Users/juanp/OneDrive/Documentos/Digital-dots/firmware-lights/components/esp_dmx/src/dmx/hal/uart.c: In function 'dmx_uart_init':
C:/Users/juanp/OneDrive/Documentos/Digital-dots/firmware-lights/components/esp_dmx/src/dmx/hal/uart.c:330:51: error: 'uart_signal_conn_t' has no member named 'module'
  330 |   periph_module_enable(uart_periph_signal[dmx_num].module);
      |                                                   ^
C:/Users/juanp/OneDrive/Documentos/Digital-dots/firmware-lights/components/esp_dmx/src/dmx/hal/uart.c:338:52: error: 'uart_signal_conn_t' has no member named 'module'
  338 |     periph_module_reset(uart_periph_signal[dmx_num].module);
      |                                                    ^
C:/Users/juanp/OneDrive/Documentos/Digital-dots/firmware-lights/components/esp_dmx/src/dmx/hal/uart.c: In function 'dmx_uart_deinit':
C:/Users/juanp/OneDrive/Documentos/Digital-dots/firmware-lights/components/esp_dmx/src/dmx/hal/uart.c:384:56: error: 'uart_signal_conn_t' has no member named 'module'
  384 |     periph_module_disable(uart_periph_signal[uart->num].module);`

**Comment by tresler** [comment]
Yes, in IDF 5.3 structure uart_signal_conn_t now don't have member "module". Have only IRQ and pins:
[IDF 5.3](https://github.com/espressif/esp-idf/blob/release/v5.3/components/soc/include/soc/uart_periph.h) vs [IDF 5.1](https://github.com/espressif/esp-idf/blob/release/v5.1/components/soc/include/soc/uart_periph.h)

**Comment by b-destoop** [comment]
It looks like this is a bug on the ESP-IDF side. 

`esp_dmx/src/dmx/hal/uart.c` refers to `uart_periph.h` and expects to find a definition of `uart_signal_conn_t` that contains a 'module' member. Except it does not exist in the version of `uart_periph.h` as given.

`uart_periph.h` is both found in 
`/esp-idf/components/soc/include/soc/uart_periph.h` 
and in
`/home/bert/esp/esp-idf/components/soc/esp32/uart_periph.c`
The second version contains the right definition of `uart_signal_conn_t` as expected, but is included for the compiler AFTER the first version, so the wrong content is selected.

Up until commit dca7c286d009024d8bacab52425c93a91ffc49c7, the version that was in /components/soc/include/soc/uart_periph.h did contain the expected definition, but was removed. [Commit found here](https://github.com/espressif/esp-idf/commit/dca7c286d009024d8bacab52425c93a91ffc49c7)

**Comment by tresler** [comment]
I found this [fork](https://github.com/davispolito/esp_dmx/tree/release/v4.1) and use #define macro for IDF version and everything work fine on ESP32-c6 with arduino-esp32 version 3.1.1. Only change .txt to .c

[uart.txt](https://github.com/user-attachments/files/18575376/uart.txt)

**Comment by gunstr** [comment]
@tresler good catch, I also had to go back to the esp-idf 5.1 version because of this. I have implemented the same changes in [this branch](https://github.com/gunstr/esp_dmx/tree/fix_for_esp-idf_5.3) but conditionally only for v.5.3 and higher. I also left out the format changes so it's easier to see what has actually happened.

I have not read up on the actual changes in the esp-idf why I have no real opinion on the correctness or completeness of the fix but I have tested with esp-idf v5.1.4 and v5.3.2 on an ESP32-S3 board and it works fine. Big thanks to @davispolito for your input.

@someweisguy let me know if you want a PR on this fix. Maybe someone can help with validation on more boards?

**Comment by gunstr** [comment]
Just realized that @davispolito already has subitted a PR (#187) with his changes...
